CREATE TABLE arthropods(id INT AUTO_INCREMENT PRIMARY KEY, userId int, subphylum VARCHAR(50) NOT NULL,
orderS VARCHAR(50) NOT NULL, family VARCHAR(50), genus VARCHAR(50), specie VARCHAR(50), 
commonName VARCHAR(50) NOT NULL, scientificName VARCHAR(50) NOT NULL, description VARCHAR(1500) NOT NULL, 
habits VARCHAR(1000) NOT NULL, habitat VARCHAR(1000) NOT NULL, impactOnHumanity VARCHAR(1500) NOT NULL,
color VARCHAR(200) NOT NULL, bodySize VARCHAR(50) NOT NULL, insertDate DATETIME NOT NULL, FOREIGN KEY (userId) REFERENCES
users(id));